Feature/db encryption
institutoazmina/penhas-app pull request #124
Opened 2023-08-07 22:00 UTC by Edely

2023-08-07 22:01 UTC, diraol commented
![](https://github.trello.services/images/mini-trello-icon.png) [Tela Modo camuflado](https://trello.com/c/Tru7K6xk/16-tela-modo-camuflado)

2023-08-07 22:18 UTC, diraol commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar banco local criptografado](https://trello.com/c/m7TGnqz6/42-implementar-banco-local-criptografado)

2023-08-17 13:01 UTC, hsvab requested changes

2023-08-17 13:01 UTC, hsvab commented on test/app/features/authentication/data/repositories/authentication_repository_test.dart
Parece estar faltando teste para verificar se vc consegue fazer o login offline (recuperar hash do banco local).

2023-09-08 13:20 UTC, renatocron commented on lib/app/app_module.dart
> +        Bind.singleton((i) => DbProvider(dbPass: '')),
eu não acho que tenha como colocar a senha required nesse estágio, pois esse é o modulo de injeção de depenncia, então esse valor é o stub, acho que a Edely deixou o password aqui só para ficar claro que existe o password para ser atualizado

uma coisa que da para fazer é trocar a class, no lugar de usar o DbProvider do modulo do author, criar o nosso propria class que extende essa e envelopa todos os outros metodos para impedir que sejam chamados no runtime sem que a senha seja iniciada com algo diferente de vazio, mas eu não sei Dart o suficiente pra saber o quão dificil/manual isso é (proxy pattern, parece que tem algo no dart https://medium.com/flutter-community/flutter-design-patterns-15-proxy-af8743b24269)

Como esse app_module é modulo que sobe o app todo, então a parte provavelmente a parte que geraria a senha também não foi instanciada ainda, então aqui geralmente os objetos são só stub mesmo

2023-09-25 09:10 UTC, Edely commented on lib/app/features/authentication/data/repositories/authentication_repository.dart
> +        final hash = await _createsHash(token: result.sessionToken ?? '');
Não sei se entendi, mas o que diz respeito ao hash só afetaria este dispositivo que ela está usando, não outros possíveis apps instalados em outros celulares.

2023-09-26 13:37 UTC, diraol commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar banco local criptografado](https://trello.com/c/m7TGnqz6/42-implementar-banco-local-criptografado)

2023-09-29 08:56 UTC, Edely commented
Converti de volta pra draft por enquanto.

Este pr precisa das features em https://github.com/institutoazmina/penhas-app/pull/126

2024-02-02 16:27 UTC, closed without merging