Configuração inicial para utilização de tarefas em background
institutoazmina/penhas-app pull request #163
Opened 2024-01-28 21:29 UTC by pedrox-hs

- Atualiza `Podfile.lock`;
- Refatoração do arquivo `main.dart`;
- Adiciona e configura a biblioteca [Workmanager](https://pub.dev/packages/workmanager);
- Sobe a versão do Kotlin para 1.8.10, necessário para integrar com a biblioteca `Workmanager`;
- Adiciona abstrações para lidar com a biblioteca `Workmanager`.

2024-01-29 03:28 UTC, pedrox-hs commented on lib/main.dart
Não sei como resolver a questão da cobertura de código:
- devo refatorar esse arquivo ainda mais para conseguir realizar mocks?
- ou, implementar testes de integração? atualmente não possuímos nenhum teste desse tipo

2024-02-03 00:24 UTC, pedrox-hs commented on lib/main.dart
> +      FirebaseAnalytics.instance.setAnalyticsCollectionEnabled(false),
é bem difícil mockar as instâncias do Firebase, a maneira ideal seria fazermos wrappers de tudo, talvez seria uma boa fazer isso num futuro com tudo, por hora eu fiz no Crashlytics e mais algumas refatorações e por conta do contexto da mudança, abri um outro PR (#165).

2024-02-03 01:59 UTC, pedrox-hs commented on lib/main.dart
PR #165

2024-02-04 00:26 UTC, diraol requested changes

2024-02-04 00:26 UTC, diraol commented on test/app/app_module_test.dart
> +      'IBackgroundTaskManager should be RemoteConfigService instance',
```suggestion
      'IBackgroundTaskManager should be BackgroundTaskManager instance',
```

2024-02-04 12:03 UTC, diraol approved these changes

2024-02-04 17:31 UTC, merged