Trata crash como erros
institutoazmina/penhas-app pull request #75
Opened 2023-04-24 14:28 UTC by pedrox-hs

- trata erros ao verificar a existencia do API token para determinar o authorization status;
- trata erro ao mapear um erro desconhecido;
- adequa os controllers para atender a esses ajustes.

2023-05-03 01:02 UTC, diraol requested changes

2023-05-03 01:02 UTC, diraol commented on lib/app/features/authentication/presentation/shared/map_failure_message.dart
> +      'Oops.. ocorreu um erro inesperado, tente novamentetarde.';
```suggestion
      'Oops.. ocorreu um erro inesperado, tente novamente mais tarde.';
```

2023-05-03 23:18 UTC, pedrox-hs commented on lib/app/features/authentication/presentation/shared/map_failure_message.dart
> +      'Oops.. ocorreu um erro inesperado, tente novamentetarde.';
valeu! acabou passando

2023-05-08 12:41 UTC, diraol approved these changes
Dentro das minhas limitações tecnológicas, me parece ok.

Eu desabilitei o "Auto Merge" para dar espaço para um review adicional :)

2023-05-10 08:37 UTC, Edely approved these changes

2023-05-12 14:32 UTC, pedrox-hs commented on lib/app/core/managers/app_configuration.dart
> +import '../data/authorization_status.dart';
Podemos ver isso sim, em um PR separado, vamos combinar isso?

2023-05-13 05:21 UTC, merged