Cobertura de teste do domain no feature Authentication
institutoazmina/penhas-app pull request #82
Opened 2023-05-13 07:10 UTC by shonorio

## Objetivo

Escrever, ou ajustar, os testes aumentar a cobertura de teste no Domain da feature Authentication

## Execução

1. Ajustado os testes para aumentar a cobertura de teste onde já existia testes
2. Criado teste onde ainda não tinha cobertura de teste

2023-05-13 13:39 UTC, diraol requested changes

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/cpf_test.dart
> +      test('constructs a Cpf with valid string', () {
```suggestion
      test('constructs a CPF with valid string', () {
```

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/cep_test.dart
> +      test('constructs a Cep with valid string', () {
```suggestion
      test('constructs a CEP with valid string', () {
```

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/cep_test.dart
> +      test('constructs a Cep with valid string without hyphen', () {
```suggestion
      test('constructs a CEP with valid string without hyphen', () {
```

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/cep_test.dart
> +          'returns invalid Cep when constructed with string with less than 8 digits',
```suggestion
          'returns invalid CEP when constructed with string with less than 8 digits',
```

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/cep_test.dart
> +      test('returns invalid Cep when constructed with null', () {
```suggestion
      test('returns invalid CEP when constructed with null', () {
```

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/cep_test.dart
> +      test('return true for equals Ceps', () {
```suggestion
      test('return true for equals CEPs', () {
```

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/cep_test.dart
> +      test('return false for different Ceps', () {
```suggestion
      test('return false for different CEPs', () {
```

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/cpf_test.dart
> +        'returns invalid Cpf when constructed with empty value',
```suggestion
        'returns invalid CPF when constructed with empty value',
```

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/cpf_test.dart
> +      test('return true for equal Cpf', () {
```suggestion
      test('return true for equal CPF', () {
```

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/cpf_test.dart
> +      test('return false for different Cpf', () {
```suggestion
      test('return false for different CPF', () {
```

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/cep_test.dart
Será que vale testar um "CEP Inválido" (com uma letra, por exemplo)?
E casos como `11111-111`, `99999-999` ?

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/cpf_test.dart
Nós estamos validando também a regra de formação do CPF (digítos de verificação)?

Se sim, talvez valha fazer um teste nesse sentido também.

Além disso, que tal testar com caracteres inválidos (letras p.ex.)?

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/sign_in_password_test.dart
> +        expect(password.rawValue, passwordString);
Isso significa que nós somos capazes de acessar o password original?
Isso não deveria ser possível, nós deveríamos fazer um hash do password "o quanto antes" e comparar só o hash do password, o valor raw nunca deveria ser armazenado.

Ou entendi errado?

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/sign_up_password_test.dart
>            expect(result.rawValue, null);
Faltou o `expect(result.mapFailure` aqui, não?

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/sign_up_password_test.dart
>            expect(result.rawValue, validPassword);
Faltou o `mapFailure` aqui também.

2023-05-13 13:39 UTC, diraol commented on test/app/features/authentication/domain/usecases/sign_up_password_test.dart
>            expect(result.rawValue, validPassword);
Idem.

2023-05-13 17:49 UTC, shonorio commented on test/app/features/authentication/domain/usecases/cpf_test.dart
> +      test('constructs a Cpf with valid string', () {
1. Estou reproduzindo o nome da classe, a classe é 'Cpf' e não 'CPF'
2. No Dart é utilizado o padrão `UpperCamelCase`, mesmo para siglas, como é o caso da class `Http` 
3. Material com o style guide do Dart [Effective Dart: Style](https://dart.dev/guides/language/effective-dart/style#identifiers)

2023-05-13 17:49 UTC, shonorio commented on test/app/features/authentication/domain/usecases/cep_test.dart
> +      test('constructs a Cep with valid string', () {
1. Estou reproduzindo o nome da classe, a classe é 'Cep' e não 'CEP'
2. No Dart é utilizado o padrão `UpperCamelCase`, mesmo para siglas, como é o caso da class `Http` 
3. Material com o style guide do Dart [Effective Dart: Style](https://dart.dev/guides/language/effective-dart/style#identifiers)

2023-05-13 17:50 UTC, shonorio commented on test/app/features/authentication/domain/usecases/cep_test.dart
> +      test('constructs a Cep with valid string without hyphen', () {
1. Estou reproduzindo o nome da classe, a classe é 'Cep' e não 'CEP'
2. No Dart é utilizado o padrão `UpperCamelCase`, mesmo para siglas, como é o caso da class `Http` 
3. Material com o style guide do Dart [Effective Dart: Style](https://dart.dev/guides/language/effective-dart/style#identifiers)

2023-05-13 17:50 UTC, shonorio commented on test/app/features/authentication/domain/usecases/cep_test.dart
> +          'returns invalid Cep when constructed with string with less than 8 digits',
1. Estou reproduzindo o nome da classe, a classe é 'Cep' e não 'CEP'
2. No Dart é utilizado o padrão `UpperCamelCase`, mesmo para siglas, como é o caso da class `Http` 
3. Material com o style guide do Dart [Effective Dart: Style](https://dart.dev/guides/language/effective-dart/style#identifiers)

2023-05-13 17:50 UTC, shonorio commented on test/app/features/authentication/domain/usecases/cep_test.dart
> +      test('returns invalid Cep when constructed with null', () {
1. Estou reproduzindo o nome da classe, a classe é 'Cep' e não 'CEP'
2. No Dart é utilizado o padrão `UpperCamelCase`, mesmo para siglas, como é o caso da class `Http` 
3. Material com o style guide do Dart [Effective Dart: Style](https://dart.dev/guides/language/effective-dart/style#identifiers)

2023-05-13 17:50 UTC, shonorio commented on test/app/features/authentication/domain/usecases/cep_test.dart
> +      test('return true for equals Ceps', () {
1. Estou reproduzindo o nome da classe, a classe é 'Cep' e não 'CEP'
2. No Dart é utilizado o padrão `UpperCamelCase`, mesmo para siglas, como é o caso da class `Http` 
3. Material com o style guide do Dart [Effective Dart: Style](https://dart.dev/guides/language/effective-dart/style#identifiers)

2023-05-13 17:50 UTC, shonorio commented on test/app/features/authentication/domain/usecases/cep_test.dart
> +      test('return false for different Ceps', () {
1. Estou reproduzindo o nome da classe, a classe é 'Cep' e não 'CEP'
2. No Dart é utilizado o padrão `UpperCamelCase`, mesmo para siglas, como é o caso da class `Http` 
3. Material com o style guide do Dart [Effective Dart: Style](https://dart.dev/guides/language/effective-dart/style#identifiers)

2023-05-13 17:51 UTC, shonorio commented on test/app/features/authentication/domain/usecases/cpf_test.dart
> +        'returns invalid Cpf when constructed with empty value',
1. Estou reproduzindo o nome da classe, a classe é 'Cpf' e não 'CPF'
2. No Dart é utilizado o padrão `UpperCamelCase`, mesmo para siglas, como é o caso da class `Http` 
3. Material com o style guide do Dart [Effective Dart: Style](https://dart.dev/guides/language/effective-dart/style#identifiers)

2023-05-13 17:51 UTC, shonorio commented on test/app/features/authentication/domain/usecases/cpf_test.dart
> +      test('return true for equal Cpf', () {
1. Estou reproduzindo o nome da classe, a classe é 'Cpf' e não 'CPF'
2. No Dart é utilizado o padrão `UpperCamelCase`, mesmo para siglas, como é o caso da class `Http` 
3. Material com o style guide do Dart [Effective Dart: Style](https://dart.dev/guides/language/effective-dart/style#identifiers)

2023-05-13 17:51 UTC, shonorio commented on test/app/features/authentication/domain/usecases/cpf_test.dart
> +      test('return false for different Cpf', () {
1. Estou reproduzindo o nome da classe, a classe é 'Cpf' e não 'CPF'
2. No Dart é utilizado o padrão `UpperCamelCase`, mesmo para siglas, como é o caso da class `Http` 
3. Material com o style guide do Dart [Effective Dart: Style](https://dart.dev/guides/language/effective-dart/style#identifiers)

2023-05-13 17:53 UTC, shonorio commented on test/app/features/authentication/domain/usecases/cpf_test.dart
No código não tem 'validação' do CPF propriamente dito, tem apenas confirmação se tem apenas números e a quantidade. É possível ter uma lib para fazer validações mais precisas, mas este não é o objetivo deste PR. Se desejar fazer isto, é recomendado fazer em outro PR

2023-05-13 17:59 UTC, shonorio commented on test/app/features/authentication/domain/usecases/sign_in_password_test.dart
> +        expect(password.rawValue, passwordString);
Isto é um [`Value Object`](https://en.wikipedia.org/wiki/Value_object) que vai existir durante o tempo que o usuário digitar a senha para cadastro, ou login, e depois some. Não tem armazenagem desta informação, isto vai para o servidor (protegido por um canal https) e lá que vai ocorrer a manipulação e armazenagem. 

Este teste só estou perguntando para o VO se ele tem o valor que foi inserido, que possivelmente será enviado para o servidor.

2023-05-13 18:10 UTC, diraol commented on test/app/features/authentication/domain/usecases/cpf_test.dart
Sim, super concordo em fazer em outra PR!

Perguntei mais para tirar a dúvida se estávamos fazendo, mas estava faltando no teste ou se não estamos fazendo at-all.

Acho que pode hora nem precisa, visto que usamos o CPF para fazer consulta/validação do nome. Isso por si só já me parece suprir essa necessidade por agora.

2023-05-14 09:32 UTC, shonorio commented on test/app/features/authentication/domain/usecases/cep_test.dart
Este ValueObject apenas garante (neste momento) que o input seja apenas números e que tenha 8 digitos. O CEP não tem uma regra de validação tal como o CPF, e qualquer sequência de número, respeitando esta duas regras básicas, são teoricamente válidas, inclusive os casos que você indicou.

https://pt.wikipedia.org/wiki/Código_de_Endereçamento_Postal

2023-05-17 12:47 UTC, shonorio commented
@diraol @pedroque  Quando forem adicionar este código a master, podem fazer por `merge` e não `squash`? Pq? É que o `squash` perde o históricos dos `commits`. Estou tomando o cuidado de realizar `commits` documentais e que pode ajudar a entender a evolução do código no futuro.

2023-05-20 03:27 UTC, diraol approved these changes

2023-05-26 14:39 UTC, merged